---
brand_name: "НПК КРИПТОНИТ"
timezone: "Europe/Moscow"

base_domain: "infra.local"
auth_fqdn: "auth.infra.local"
nextcloud_fqdn: "cloud.infra.local"
onlyoffice_fqdn: "office.infra.local"

docker_infra_network: "infra_internal"

caddy_admin_email: "admin@infra.local"

authentik_upstream: "authentik-server:9000"
nextcloud_upstream: "nextcloud-app:80"
onlyoffice_upstream: "onlyoffice:80"
