---
brand_name: "НПК КРИПТОНИТ"
timezone: "Europe/Moscow"

base_domain: "infra.local"
auth_domain: "auth.{{ base_domain }}"
cloud_domain: "cloud.{{ base_domain }}"
office_domain: "office.{{ base_domain }}"

infra_network_name: "infra_internal"

private_ca_hostname: "private-ca"
private_ca_port: 9000
private_ca_name: "Infra Private CA"
internal_ca_url: >-
  https://{{ private_ca_hostname }}:{{ private_ca_port }}/acme/acme/directory

caddy_admin_email: "admin@{{ base_domain }}"
caddy_config_auto_https: true

authentik_db_name: authentik
authentik_db_user: authentik
authentik_bootstrap_email: "admin@{{ base_domain }}"
authentik_bootstrap_password: "ChangeMe!123"

authentik_upstream: "http://authentik-server:9000"
nextcloud_upstream: "http://nextcloud-web:80"
onlyoffice_upstream: "http://onlyoffice:80"

nextcloud_db_name: nextcloud
nextcloud_db_user: nextcloud
nextcloud_admin_user: admin
nextcloud_admin_password: "AdminPass123!"

private_ca_image: "smallstep/step-ca:0.27.3"
caddy_image: "caddy:2.7"
authentik_images:
  server: "ghcr.io/goauthentik/server:2024.2.2"
  worker: "ghcr.io/goauthentik/server:2024.2.2"
authentik_postgres_image: "postgres:15-alpine"
authentik_redis_image: "redis:7-alpine"
nextcloud_image: "nextcloud:27-apache"
nextcloud_cron_image: "nextcloud:27-apache"
nextcloud_mariadb_image: "mariadb:10.11"
nextcloud_redis_image: "redis:7-alpine"
onlyoffice_image: "onlyoffice/documentserver:7.5"

offline_images_cache_dir: "{{ playbook_dir | default('.') }}/images"
offline_images_target_dir: /opt/kryptonit-stack/images
offline_images_force_fetch: false
offline_images_catalog:
  - image: "{{ private_ca_image }}"
    archive: step-ca_0.27.3.tar
  - image: "{{ caddy_image }}"
    archive: caddy_2.7.tar
  - image: "{{ authentik_images.server }}"
    archive: authentik_2024.2.2.tar
  - image: "{{ authentik_postgres_image }}"
    archive: postgres_15-alpine.tar
  - image: "{{ authentik_redis_image }}"
    archive: redis_7-alpine.tar
  - image: "{{ nextcloud_image }}"
    archive: nextcloud_27-apache.tar
  - image: "{{ nextcloud_mariadb_image }}"
    archive: mariadb_10.11.tar
  - image: "{{ onlyoffice_image }}"
    archive: onlyoffice_documentserver_7.5.tar

preflight_enable_disk_checks: false
