- name: Bootstrap local caches (registry mirror + apt-cacher-ng)
  hosts: all
  gather_facts: false
  roles:
    - cache

- name: Ensure Docker on all hosts
  hosts: all
  gather_facts: true
  vars_files:
    - group_vars/secrets.vault.yml
  collections:
    - community.docker
    - community.general
    - ansible.posix
  roles:
    - docker

- name: Central TLS reverse proxy (Caddy)
  hosts: proxyhost
  vars_files:
    - group_vars/secrets.vault.yml
  collections:
    - community.docker
    - community.general
    - ansible.posix
  roles:
    - caddy_proxy

- name: Authentik SSO
  hosts: authhost
  vars_files:
    - group_vars/secrets.vault.yml
  collections:
    - community.docker
    - community.general
    - ansible.posix
  roles:
    - authentik

- name: Nextcloud
  hosts: cloudhost
  vars_files:
    - group_vars/secrets.vault.yml
  collections:
    - community.docker
    - community.general
    - ansible.posix
  roles:
    - nextcloud

- name: OnlyOffice DocumentServer
  hosts: officehost
  vars_files:
    - group_vars/secrets.vault.yml
  collections:
    - community.docker
    - community.general
    - ansible.posix
  roles:
    - onlyoffice
