---
- name: Ensure Nextcloud project dir
  ansible.builtin.file:
    path: /opt/nextcloud
    state: directory
    mode: '0755'

- name: Ensure Nextcloud application directories
  ansible.builtin.file:
    path: "/opt/nextcloud/{{ item }}"
    state: directory
    owner: "{{ nextcloud_fs_owner }}"
    group: "{{ nextcloud_fs_group }}"
    mode: "{{ nextcloud_fs_mode }}"
  loop:
    - data
    - apps
    - config

- name: Ensure Nextcloud service state directories
  ansible.builtin.file:
    path: "/opt/nextcloud/{{ item.name }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { name: "db", owner: "root", group: "root", mode: "0750" }
    - { name: "redis", owner: "root", group: "root", mode: "0750" }

- name: Render Redis config snippet
  ansible.builtin.template:
    src: redis.config.php.j2
    dest: /opt/nextcloud/config/redis.config.php
    owner: "{{ nextcloud_fs_owner }}"
    group: "{{ nextcloud_fs_group }}"
    mode: '0640'

# roles/nextcloud/templates/docker-compose.yml.j2 должен существовать
- name: Render Nextcloud docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/nextcloud/docker-compose.yml
    mode: '0644'

- name: Run Nextcloud stack
  community.docker.docker_compose_v2:
    project_src: /opt/nextcloud
    state: present
    pull: missing
