---
- name: Ensure Nextcloud project dir
  ansible.builtin.file:
    path: "{{ nextcloud_project_path }}"
    state: directory
    mode: '0755'

- name: Ensure Nextcloud data directories
  ansible.builtin.file:
    path: "{{ nextcloud_project_path }}/{{ item }}"
    state: directory
    owner: "{{ nextcloud_fs_owner }}"
    group: "{{ nextcloud_fs_group }}"
    mode: "{{ nextcloud_fs_mode }}"
  loop:
    - data
    - apps
    - config
    - db
    - redis

- name: Render Redis config snippet
  ansible.builtin.template:
    src: redis.config.php.j2
    dest: "{{ nextcloud_project_path }}/config/redis.config.php"
    owner: "{{ nextcloud_fs_owner }}"
    group: "{{ nextcloud_fs_group }}"
    mode: '0640'

# roles/nextcloud/templates/docker-compose.yml.j2 должен существовать
- name: Render Nextcloud docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ nextcloud_project_path }}/{{ nextcloud_compose_file }}"
    mode: '0644'

- name: Run Nextcloud stack
  community.docker.docker_compose_v2:
    project_src: "{{ nextcloud_project_path }}"
    state: present
    pull: "{{ nextcloud_compose_pull }}"
