---
- name: Ensure Nextcloud directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ nextcloud_project_path }}"
    - "{{ nextcloud_data_path }}"
    - "{{ nextcloud_db_path }}"
    - "{{ nextcloud_redis_path }}"

- name: Deploy Nextcloud stack
  community.docker.docker_compose_v2:
    project_name: nextcloud
    definition:
      version: '3.9'
      services:
        nextcloud-mariadb:
          image: "{{ nextcloud_mariadb_image }}"
          pull_policy: never
          container_name: nextcloud-mariadb
          restart: unless-stopped
          environment:
            MYSQL_ROOT_PASSWORD: >-
              {{ nextcloud_db_root_password | mandatory }}
            MYSQL_DATABASE: "{{ nextcloud_db_name }}"
            MYSQL_USER: "{{ nextcloud_db_user }}"
            MYSQL_PASSWORD: >-
              {{ nextcloud_db_password | mandatory }}
          volumes:
            - >-
              {{ nextcloud_db_path }}:/var/lib/mysql
          healthcheck:
            test:
              - CMD-SHELL
              - >-
                mysqladmin ping -h localhost
                -p{{ nextcloud_db_root_password | mandatory }} || exit 1
            interval: 30s
            timeout: 10s
            retries: 5
          networks:
            - "{{ infra_network_name }}"

        nextcloud-redis:
          image: "{{ nextcloud_redis_image }}"
          pull_policy: never
          container_name: nextcloud-redis
          restart: unless-stopped
          command:
            - redis-server
            - --requirepass
            - "{{ nextcloud_redis_password | mandatory }}"
          volumes:
            - >-
              {{ nextcloud_redis_path }}:/data
          healthcheck:
            test:
              - CMD-SHELL
              - >-
                redis-cli -a {{ nextcloud_redis_password | mandatory }}
                ping | grep PONG
            interval: 30s
            timeout: 10s
            retries: 5
          networks:
            - "{{ infra_network_name }}"

        nextcloud-web:
          image: "{{ nextcloud_image }}"
          pull_policy: never
          container_name: nextcloud-web
          restart: unless-stopped
          environment:
            MYSQL_HOST: nextcloud-mariadb
            MYSQL_DATABASE: "{{ nextcloud_db_name }}"
            MYSQL_USER: "{{ nextcloud_db_user }}"
            MYSQL_PASSWORD: >-
              {{ nextcloud_db_password | mandatory }}
            MYSQL_ROOT_PASSWORD: >-
              {{ nextcloud_db_root_password | mandatory }}
            NEXTCLOUD_TRUSTED_DOMAINS: >-
              {{ nextcloud_trusted_domains | join(' ') }}
            NEXTCLOUD_ADMIN_USER: >-
              {{ nextcloud_admin_user | default('admin') }}
            NEXTCLOUD_ADMIN_PASSWORD: >-
              {{ nextcloud_admin_password | default('AdminPass123!') }}
            NEXTCLOUD_DATA_DIR: /var/www/html/data
            REDIS_HOST: nextcloud-redis
            REDIS_HOST_PASSWORD: >-
              {{ nextcloud_redis_password | mandatory }}
            APACHE_DISABLE_REWRITE_IP: "1"
            PHP_MEMORY_LIMIT: >-
              {{ nextcloud_php_memory_limit }}
            TZ: "{{ nextcloud_timezone }}"
          volumes:
            - >-
              {{ nextcloud_data_path }}:/var/www/html
          expose:
            - "80"
          depends_on:
            nextcloud-mariadb:
              condition: service_healthy
            nextcloud-redis:
              condition: service_healthy
          healthcheck:
            test:
              - CMD-SHELL
              - pidof apache2
            interval: 60s
            timeout: 10s
            retries: 5
          networks:
            - "{{ infra_network_name }}"

        nextcloud-cron:
          image: "{{ nextcloud_cron_image }}"
          pull_policy: never
          container_name: nextcloud-cron
          restart: unless-stopped
          entrypoint: ["/cron.sh"]
          environment:
            MYSQL_HOST: nextcloud-mariadb
            MYSQL_DATABASE: "{{ nextcloud_db_name }}"
            MYSQL_USER: "{{ nextcloud_db_user }}"
            MYSQL_PASSWORD: >-
              {{ nextcloud_db_password | mandatory }}
            MYSQL_ROOT_PASSWORD: >-
              {{ nextcloud_db_root_password | mandatory }}
            NEXTCLOUD_DATA_DIR: /var/www/html/data
            REDIS_HOST: nextcloud-redis
            REDIS_HOST_PASSWORD: >-
              {{ nextcloud_redis_password | mandatory }}
            TZ: "{{ nextcloud_timezone }}"
          volumes:
            - >-
              {{ nextcloud_data_path }}:/var/www/html
          depends_on:
            nextcloud-mariadb:
              condition: service_healthy
            nextcloud-redis:
              condition: service_healthy
          networks:
            - "{{ infra_network_name }}"
          healthcheck:
            test:
              - CMD-SHELL
              - >-
                php -r 'exit(0);'
            interval: 60s
            timeout: 10s
            retries: 5
      networks:
        "{{ infra_network_name }}":
          external: true
