---
- name: Verify Docker CLI is available
  ansible.builtin.command: docker --version
  register: preflight_docker_version
  changed_when: false
  tags:
    - preflight

- name: Verify Docker Compose is available
  ansible.builtin.command: docker compose version
  register: preflight_compose_version
  changed_when: false
  tags:
    - preflight

- name: Display Docker version information
  ansible.builtin.debug:
    msg: "{{ preflight_docker_version.stdout }}"
  when: preflight_docker_version.stdout is defined
  tags:
    - preflight

- name: Display Docker Compose version information
  ansible.builtin.debug:
    msg: "{{ preflight_compose_version.stdout }}"
  when: preflight_compose_version.stdout is defined
  tags:
    - preflight

- name: Ensure required ports are free
  ansible.builtin.wait_for:
    port: "{{ item }}"
    state: stopped
    timeout: 1
  loop: "{{ preflight_ports }}"
  loop_control:
    label: "port {{ item }}"
  tags:
    - preflight

- name: Set default root mount if not provided
  ansible.builtin.set_fact:
    preflight_root_mount: "{{ preflight_root_mount | default('/') }}"
  when: preflight_enable_disk_checks | default(false) | bool
  tags:
    - preflight

- name: Calculate available disk space on root (bytes)
  ansible.builtin.set_fact:
    preflight_available_bytes: >-
      {{
        (
          ansible_facts.mounts
          | default(ansible_facts.ansible_mounts | default([]))
        )
        | selectattr('mount', 'equalto', preflight_root_mount | default('/'))
        | map(attribute='size_available')
        | first
        | default(0)
      }}
  when: preflight_enable_disk_checks | default(false) | bool
  tags:
    - preflight

- name: Calculate required disk space on root (bytes)
  ansible.builtin.set_fact:
    preflight_required_bytes: >-
      {{
        (
          (preflight_root_required_gib | default(5) | float)
          * (preflight_bytes_per_gib | default(1073741824) | int)
        ) | int
      }}
  when: preflight_enable_disk_checks | default(false) | bool
  tags:
    - preflight

- name: Convert to GiB
  ansible.builtin.set_fact:
    preflight_root_available_gib: >-
      {{ (preflight_available_bytes | int) / (1024**3) }}
  when: preflight_enable_disk_checks | default(false) | bool
  tags:
    - preflight

- name: Assert sufficient disk space is available
  ansible.builtin.assert:
    that:
      - >
        (preflight_available_bytes | default(0) | int)
        >= (preflight_required_bytes | default(0) | int)
      - >
        (preflight_root_available_gib | default(0) | float)
        >= (preflight_root_required_gib | default(5) | float)
    fail_msg: |-
      Требуется минимум {{ preflight_root_required_gib | default(5) }} ГиБ
      на {{ preflight_root_mount | default('/') }}.
      Доступно:
        {{ preflight_root_available_gib | default('0') | round(2) }} ГиБ.
  when: preflight_enable_disk_checks | default(false) | bool
  tags:
    - preflight

- name: Warn when swap is disabled
  ansible.builtin.debug:
    msg: >-
      Swap не настроен. Рассмотрите возможность включения swap при
      высоких нагрузках.
  when: (ansible_facts.ansible_swaptotal_mb | default(0)) | int == 0
  tags:
    - preflight
