---
- name: Restart Nextcloud stack  # noqa command-instead-of-module
  ansible.builtin.command:
    cmd: >-
      docker compose --ansi never
      -f {{ nextcloud_compose_file }}
      up -d --remove-orphans
    chdir: "{{ nextcloud_project_path }}"
  changed_when: true

