---
- name: Ensure OnlyOffice project dir
  ansible.builtin.file:
    path: "{{ onlyoffice_project_path }}"
    state: directory
    mode: '0755'

- name: Ensure OnlyOffice data directories
  ansible.builtin.file:
    path: "{{ onlyoffice_project_path }}/{{ item }}"
    state: directory
    mode: '0750'
  loop:
    - data
    - log
    - lib

# roles/onlyoffice/templates/docker-compose.yml.j2 должен существовать
- name: Render OnlyOffice docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ onlyoffice_project_path }}/{{ onlyoffice_compose_file }}"
    mode: '0644'
  notify: Apply OnlyOffice stack

- name: Ensure OnlyOffice stack is running  # noqa command-instead-of-module
  ansible.builtin.command:
    cmd: >-
      docker compose -f {{ onlyoffice_compose_file }}
      up -d --remove-orphans
  args:
    chdir: "{{ onlyoffice_project_path }}"
  register: onlyoffice_compose
  failed_when: onlyoffice_compose.rc != 0
  changed_when: >-
    onlyoffice_compose.rc == 0 and (
      onlyoffice_compose.stdout is search(
        '(?i)(Creating|Recreating|Starting|Started|Pulling|Downloading|Building|Removing)'
      )
      or onlyoffice_compose.stderr is search(
        '(?i)(Creating|Recreating|Starting|Started|Pulling|Downloading|Building|Removing)'
      )
    )
