---
- name: Ensure OnlyOffice directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ onlyoffice_project_path }}"
    - "{{ onlyoffice_project_path }}/data"
    - "{{ onlyoffice_project_path }}/logs"

- name: Deploy OnlyOffice Document Server
  community.docker.docker_compose_v2:
    project_name: onlyoffice
    definition:
      version: '3.9'
      services:
        onlyoffice:
          image: "{{ onlyoffice_image }}"
          container_name: onlyoffice
          restart: unless-stopped
          environment:
            JWT_ENABLED: >-
              {{ onlyoffice_jwt_enabled | ternary('true', 'false') }}
            JWT_SECRET: >-
              {{ onlyoffice_jwt_secret | mandatory }}
            JWT_HEADER: AuthorizationJwt
          volumes:
            - >-
              {{ onlyoffice_project_path }}/data:/var/www/onlyoffice/Data
            - >-
              {{ onlyoffice_project_path }}/logs:/var/log/onlyoffice
          expose:
            - "80"
          healthcheck:
            test:
              - CMD-SHELL
              - pgrep supervisord
            interval: 30s
            timeout: 10s
            retries: 5
          networks:
            - "{{ infra_network_name }}"
      networks:
        "{{ infra_network_name }}":
          external: true
