---
- name: Create Caddy dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ caddy_proxy_project_path }}"
    - "{{ caddy_proxy_project_path }}/data"
    - "{{ caddy_proxy_project_path }}/config"

- name: Render Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ caddy_proxy_project_path }}/Caddyfile"
    owner: root
    group: root
    mode: '0644'

- name: Write docker-compose.yml for Caddy
  ansible.builtin.copy:
    dest: "{{ caddy_proxy_project_path }}/{{ caddy_proxy_compose_file }}"
    owner: root
    group: root
    mode: '0644'
    content: |
      services:
        caddy:
          image: {{ caddy_proxy_image }}
          container_name: caddy
          ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
          networks:
            - infra
          healthcheck:
            test: ["CMD", "caddy", "version"]
            interval: 30s
            timeout: 5s
            retries: 3
          volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
            - ./data:/data
            - ./config:/config
          restart: unless-stopped
      networks:
        infra:
          external: true
          name: {{ docker_infra_network }}

- name: Run Caddy via compose
  community.docker.docker_compose_v2:
    project_src: "{{ caddy_proxy_project_path }}"
    state: present
    pull: "{{ caddy_proxy_compose_pull }}"
