---
- name: Fail if unsupported OS family
  ansible.builtin.assert:
    that:
      - ansible_os_family in ['Debian']
    fail_msg: "Currently only Debian/Ubuntu family is supported."

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Install prerequisites
  apt:
    name: [ca-certificates, curl, gnupg, lsb-release]
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Add Docker GPG key
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  when: ansible_os_family == 'Debian'

- name: Resolve Docker architecture
  set_fact:
    docker_repo_arch: "{{ docker_arch_map.get(ansible_architecture | default('amd64'), ansible_architecture | default('amd64')) }}"

- name: Add Docker repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ docker_repo_arch }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
  when: ansible_os_family == 'Debian'

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Ensure docker service enabled
  systemd:
    name: docker
    state: started
    enabled: true

- name: Ensure shared Docker network exists
  community.docker.docker_network:
    name: "{{ docker_infra_network }}"
    state: present
