---
- name: Ensure Authentik project dir
  ansible.builtin.file:
    path: "{{ authentik_project_path }}"
    state: directory
    mode: '0755'

- name: Ensure Authentik data directories
  ansible.builtin.file:
    path: "{{ authentik_project_path }}/{{ item }}"
    state: directory
    mode: '0750'
  loop:
    - postgres
    - redis
    - media
    - config

# Предполагаем, что шаблон уже есть в роли:
# roles/authentik/templates/docker-compose.yml.j2
- name: Render Authentik docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ authentik_project_path }}/{{ authentik_compose_file }}"
    mode: '0644'

- name: Run Authentik stack
  community.docker.docker_compose_v2:
    project_src: "{{ authentik_project_path }}"
    state: present
    pull: "{{ authentik_compose_pull }}"
