---
# Demo secrets for local development. Replace with ansible-vault encrypted values in real setups.
private_ca_password: "dev-private-ca-pass!"

authentik_db_password: "dev-authentik-db-pass"
authentik_redis_password: "dev-authentik-redis"
authentik_secret_key: "dev-authentik-secret"
authentik_bootstrap_token: ""

nextcloud_db_root_password: "dev-nextcloud-root"
nextcloud_db_password: "dev-nextcloud-pass"
nextcloud_redis_password: "dev-nextcloud-redis"

onlyoffice_jwt_secret: "dev-onlyoffice-jwt"

caddy_config_auto_https: false
