---
- name: Deploy application stack
  hosts: infra
  become: true
  gather_facts: false
  roles:
    - role: private_ca
      tags:
        - private_ca
    - role: caddy
      tags:
        - caddy
    - role: authentik
      tags:
        - authentik
    - role: nextcloud
      tags:
        - nextcloud
    - role: onlyoffice
      tags:
        - onlyoffice
