---
- name: Base container stack preparation
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: docker
      tags:
        - docker
    - role: network
      tags:
        - network
